# Generated by Django 5.2.7 on 2025-11-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(unique=True, verbose_name="Номер корпуса"),
                ),
                (
                    "position_left",
                    models.CharField(
                        help_text="Отступ от левого края",
                        max_length=20,
                        verbose_name="Позиция слева",
                    ),
                ),
                (
                    "position_top",
                    models.CharField(
                        help_text="Отступ от верхнего края",
                        max_length=20,
                        verbose_name="Позиция сверху",
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        help_text="Ширина корпуса", max_length=20, verbose_name="Ширина"
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        help_text="Высота корпуса", max_length=20, verbose_name="Высота"
                    ),
                ),
                (
                    "clip_path",
                    models.TextField(
                        blank=True,
                        help_text="CSS polygon для сложных форм (оставьте пусто если обычный прямоугольник)",
                        verbose_name="Форма корпуса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корпус",
                "verbose_name_plural": "Корпуса",
                "ordering": ["number"],
            },
        ),
    ]
