# Generated by Django 5.2.7 on 2025-11-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="border_radius",
            field=models.CharField(
                blank=True,
                help_text="Например: 10px или 10px 0 10px 0",
                max_length=50,
                verbose_name="Скругление углов (border-radius)",
            ),
        ),
    ]
