# Generated by Django 5.2.7 on 2025-11-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_building_border_radius"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="text_padding_left",
            field=models.CharField(
                blank=True,
                help_text="Например: 15px",
                max_length=20,
                verbose_name="Отступ текста слева",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="text_padding_top",
            field=models.CharField(
                blank=True,
                help_text="Например: 10px или 2em",
                max_length=20,
                verbose_name="Отступ текста сверху",
            ),
        ),
    ]
