# Generated by Django 5.2.7 on 2026-01-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_building_text_padding_left_building_text_padding_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="floors_count",
            field=models.IntegerField(default=5, verbose_name="Количество этажей"),
        ),
    ]
