# Generated by Django 5.2.8 on 2026-03-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_building_floors_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='z_index',
            field=models.CharField(blank=True, help_text='Например: 10 или 100', max_length=20, verbose_name='Слой (z-index)'),
        ),
    ]
