# Generated by Django 5.2.7 on 2026-03-31 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_building_z_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("floor", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("room", "Аудитория"),
                            ("toilet", "Туалет"),
                            ("lift", "Лифт"),
                            ("staircase", "Лестница"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.building"
                    ),
                ),
            ],
        ),
    ]
